services:
  web:
    build:
      context: ../../../apps/web
      dockerfile: ../../infra/web/docker/Dockerfile
    image: jupiter-web:local
    env_file:
      - web.env
    ports:
      - "80:5173"
    extra_hosts:
      - "host.docker.internal:host-gateway"
