package com.platform.jupiter.foodshow;

public record FoodShowEntryView(
        String showSlug,
        String showTitle,
        String categorySlug,
        String categoryName,
        String participantSlug,
        String participantName,
        String personaLabel,
        String roleLabel,
        String oneLiner,
        String cuisineLabel,
        String venueSlug,
        String venueName,
        String venueType,
        String areaLabel,
        String roadAddress,
        String nearestStation,
        java.math.BigDecimal latitude,
        java.math.BigDecimal longitude,
        String signatureItem,
        String shortNote,
        String programNote,
        String placeUrl,
        String mapUrl,
        String reservationUrl,
        String reservationProvider,
        String sourceUrl,
        String sourceName,
        String sourceNote,
        String discoveryStatus,
        String locationStatus,
        String cardStatus,
        int sortOrder) {
}
