apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: jupiter-web-env
    envs:
      - web.env

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
