apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiter-api
  namespace: jupiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupiter-api
  template:
    metadata:
      labels:
        app: jupiter-api
    spec:
      containers:
        - name: api
          image: jupiter-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: jupiter-api-env
